"use client";

import { useState } from "react";
import { useApp } from "@/context/AppContext";

export default function ClientDocuments() {
  const { listings, bids, currentUser, rateVendor, vendorRatings } = useApp();
  const [ratingModal, setRatingModal] = useState<{ open: boolean; listingId: string | null; vendorId: string | null; vendorName: string | null }>({ open: false, listingId: null, vendorId: null, vendorName: null });
  const [ratingVals, setRatingVals] = useState({ overall: 5, audit: 5, timeliness: 5, compliance: 5, comment: "" });

  // Only completed listings for this client
  const completedListings = listings.filter(l =>
    l.userId === currentUser?.id && l.complianceStatus === "verified"
  );

  const getWinBid = (listingId: string) =>
    bids.find(b => b.listingId === listingId && b.status === "accepted");

  const COMPLIANCE_DOCS = [
    { key: "form6Url" as const, label: "Form 6", icon: "description" },
    { key: "weightSlipEmptyUrl" as const, label: "Weight Slip (Empty Vehicle)", icon: "scale" },
    { key: "weightSlipLoadedUrl" as const, label: "Weight Slip (Loaded Vehicle)", icon: "scale" },
    { key: "recyclingCertUrl" as const, label: "Recycling Certificate", icon: "recycling" },
    { key: "disposalCertUrl" as const, label: "Disposal Certificate", icon: "delete_forever" },
  ];

  const totalDocs = completedListings.reduce((s, l) => {
    return s + COMPLIANCE_DOCS.filter(d => !!l[d.key]).length;
  }, 0);

  const generateReport = (listing: typeof listings[0]) => {
    const win = getWinBid(listing.id);
    const content = `COMPLIANCE SUMMARY REPORT
==============================================================
WeConnect E-Waste Aggregator Platform

Report For   : ${listing.title}
Listing ID   : ${listing.id}
Client       : ${listing.userName}
Vendor       : ${win?.vendorName || "—"}
Weight       : ${listing.weight} KG
Location     : ${listing.location}
Pickup Date  : ${listing.pickupScheduledDate ? new Date(listing.pickupScheduledDate).toLocaleDateString("en-IN") : "—"}

COMPLIANCE STATUS: VERIFIED ✓

Documents on file:
${COMPLIANCE_DOCS.map(d => `  ${listing[d.key] ? "✓" : "✗"} ${d.label}`).join("\n")}

Amount Recovered : ₹${win?.amount.toLocaleString() || "—"}
WeConnect Fee    : ₹${Math.round((win?.amount || 0) * 0.05).toLocaleString()}
Net to Client    : ₹${Math.round((win?.amount || 0) * 0.95).toLocaleString()}

Generated by WeConnect Platform · ${new Date().toLocaleString("en-IN")}
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `WeConnect_Compliance_${listing.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-20">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-3xl font-headline font-extrabold tracking-tight text-[color:var(--color-on-surface)]">Compliance Documents</h2>
          <p className="text-[color:var(--color-on-surface-variant)] mt-1">Download verified compliance certificates for completed e-waste disposal.</p>
        </div>
        <div className="text-right">
          <p className="text-3xl font-black text-primary">{totalDocs}</p>
          <p className="text-xs font-bold text-slate-500 uppercase">Docs Available</p>
        </div>
      </div>

      {completedListings.length === 0 ? (
        <div className="card p-20 text-center border-2 border-dashed border-slate-200">
          <span className="material-symbols-outlined text-6xl text-slate-300 mb-4 block">verified</span>
          <h3 className="text-xl font-bold text-slate-900">No Compliance Documents Yet</h3>
          <p className="text-slate-500 mt-2">Documents become available once your e-waste disposal is fully verified by WeConnect.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {completedListings.map(listing => {
            const win = getWinBid(listing.id);

            return (
              <div key={listing.id} className="card p-0 overflow-hidden border-2 border-emerald-200">
                <div className="p-5 bg-emerald-50/50 border-b border-emerald-100 flex items-start justify-between gap-4">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-black text-slate-400">{listing.id}</span>
                      <span className="text-[9px] px-2.5 py-0.5 rounded-full font-black uppercase bg-emerald-100 text-emerald-700">
                        Disposal Verified
                      </span>
                    </div>
                    <h3 className="font-bold text-slate-900">{listing.title}</h3>
                    <p className="text-xs text-slate-500 mt-0.5">
                      {listing.location} · {listing.weight} KG · Vendor: {win?.vendorName || "—"}
                    </p>
                    {listing.pickupScheduledDate && (
                      <p className="text-xs text-slate-500 mt-0.5">
                        Pickup: {new Date(listing.pickupScheduledDate).toLocaleDateString("en-IN")}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {!vendorRatings.some(r => r.listingId === listing.id) && (
                      <button
                        onClick={() => setRatingModal({ open: true, listingId: listing.id, vendorId: win?.vendorId || "", vendorName: win?.vendorName || "" })}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl border border-emerald-200 text-emerald-700 text-xs font-bold hover:bg-emerald-100"
                      >
                        <span className="material-symbols-outlined text-sm">star</span>
                        Rate Vendor
                      </button>
                    )}
                    <button
                      onClick={() => generateReport(listing)}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold hover:bg-emerald-700"
                    >
                      <span className="material-symbols-outlined text-sm">summarize</span>
                      Full Report
                    </button>
                  </div>
                </div>

                <div className="p-5">
                  {/* Environmental impact */}
                  <div className="flex gap-4 mb-5 p-3 bg-emerald-50 rounded-xl border border-emerald-100">
                    <span className="material-symbols-outlined text-emerald-600">eco</span>
                    <div className="flex gap-6 text-xs">
                      <div>
                        <p className="font-black text-emerald-800">{(listing.weight * 2.4).toFixed(1)} kg CO2e</p>
                        <p className="text-emerald-600">Carbon Offset</p>
                      </div>
                      <div>
                        <p className="font-black text-emerald-800">{(listing.weight * 15).toFixed(0)} kWh</p>
                        <p className="text-emerald-600">Energy Saved</p>
                      </div>
                      <div>
                        <p className="font-black text-emerald-800">₹{Math.round((win?.amount || 0) * 0.95).toLocaleString()}</p>
                        <p className="text-emerald-600">Net Recovered</p>
                      </div>
                    </div>
                  </div>

                  {/* Document grid */}
                  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                    {COMPLIANCE_DOCS.map(doc => {
                      const url = listing[doc.key];
                      return (
                        <div key={doc.key} className={`p-3 rounded-xl border text-center ${url ? "border-emerald-200 bg-emerald-50 hover:bg-emerald-100" : "border-dashed border-slate-200 bg-slate-50 opacity-50"}`}>
                          <span className={`material-symbols-outlined text-xl block mb-1 ${url ? "text-emerald-600" : "text-slate-300"}`}>{doc.icon}</span>
                          <p className="text-[9px] font-black uppercase text-slate-600 leading-tight mb-2">{doc.label}</p>
                          {url ? (
                            <a href={url} download
                              className="text-[9px] font-black text-primary px-2 py-1 rounded-lg bg-primary/10 hover:bg-primary hover:text-white transition-colors block">
                              Download
                            </a>
                          ) : (
                            <p className="text-[9px] text-slate-400">Not available</p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Vendor Rating Modal */}
      {ratingModal.open && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-md p-6 space-y-5">
            <div>
              <h3 className="text-xl font-headline font-extrabold text-slate-900">Rate Vendor</h3>
              <p className="text-sm text-slate-500">Rate {ratingModal.vendorName}'s performance on this deal.</p>
            </div>
            
            <div className="space-y-4">
              {[
                { key: 'overall', label: 'Overall Experience' },
                { key: 'audit', label: 'Audit Accuracy' },
                { key: 'timeliness', label: 'Pickup Timeliness' },
                { key: 'compliance', label: 'Compliance Handling' },
              ].map(cat => (
                <div key={cat.key} className="flex items-center justify-between">
                  <span className="text-sm font-bold text-slate-700">{cat.label}</span>
                  <div className="flex gap-1">
                    {[1, 2, 3, 4, 5].map(star => (
                      <button 
                        key={star}
                        onClick={() => setRatingVals(p => ({ ...p, [cat.key]: star }))}
                        className="group"
                      >
                        <span className={`material-symbols-outlined text-xl transition-all ${
                          star <= (ratingVals[cat.key as keyof typeof ratingVals] as number)
                            ? "text-amber-400" : "text-slate-200 hover:text-amber-200"
                        }`} style={{ fontVariationSettings: star <= (ratingVals[cat.key as keyof typeof ratingVals] as number) ? "'FILL' 1" : "" }}>
                          star
                        </span>
                      </button>
                    ))}
                  </div>
                </div>
              ))}
              
              <div>
                <label className="label">Review Comment (Optional)</label>
                <textarea
                  className="input-base min-h-[80px] resize-none"
                  placeholder="Share details about your experience..."
                  value={ratingVals.comment}
                  onChange={e => setRatingVals(p => ({ ...p, comment: e.target.value }))}
                />
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-2">
              <button
                onClick={() => setRatingModal({ open: false, listingId: null, vendorId: null, vendorName: null })}
                className="px-5 py-2.5 rounded-xl border border-slate-200 text-sm font-bold text-slate-700 hover:bg-slate-50"
              >Cancel</button>
              <button
                onClick={() => {
                  if (ratingModal.listingId && ratingModal.vendorId && ratingModal.vendorName) {
                    rateVendor(ratingModal.listingId, ratingModal.vendorId, ratingModal.vendorName, ratingVals.overall, ratingVals.audit, ratingVals.timeliness, ratingVals.compliance, ratingVals.comment);
                    setRatingModal({ open: false, listingId: null, vendorId: null, vendorName: null });
                  }
                }}
                className="px-5 py-2.5 rounded-xl bg-amber-500 text-white text-sm font-bold hover:bg-amber-600"
              >Submit Rating</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
